minor updates to most scripts

diff --git a/ghclone b/ghclone
--- a/ghclone
+++ b/ghclone
@@ -1,24 +1,24 @@
 #!/bin/sh
-# set -eou pipefail
-MYGITPATH="${HOME}/Gits"
-REPOURL="$1"
-REPONAME="$(/usr/bin/echo \""$REPOURL"\" | awk -F"/" '{print $NF}' | cut -d "." -f 1)"
-if [ ! -d "$MYGITPATH" ]; then
-	mkdir -p "$MYGITPATH"
+# checks if repo exists, if not clones it to ~/Gits by default
+my_git_path="${HOME}/Gits"
+repo_url="${1}"
+repo_name="$(/usr/bin/echo \""${repo_url}"\" | awk -F"/" '{print $NF}' | cut -d "." -f 1)"
+if [ ! -d "${my_git_path}" ]; then
+	mkdir -p "${my_git_path}"
 fi
-if [ -z "$REPOURL" ]; then
+if [ -z "${repo_url}" ]; then
     printf "\n\tusage: ghclone <cloneurl>\n" && exit 1
 fi
-if [ -z "$REPONAME" ]; then
-	printf "\n\tunable to get data: \"%s\"\n" "$REPONAME" && exit 1
+if [ -z "${repo_name}" ]; then
+	printf "\n\tunable to get data: \"%s\"\n" "${repo_name}" && exit 1
 fi
-if [ -d "$MYGITPATH/$REPONAME" ]; then
-	printf "\n\tRepo \"%s\" already exists in \"%s\"\n" "$REPONAME" "$MYGITPATH" && exit 1
+if [ -d "${my_git_path}/${repo_name}" ]; then
+	printf "\n\tRepo \"%s\" already exists in \"%s\"\n" "${repo_name}" "${my_git_path}" && exit 1
 fi
-printf "gitpath: %s\nrepourl: %s\nreponame: %s\n" "$MYGITPATH" "$REPOURL" "$REPONAME"
-# pushd "$MYGITPATH" || exit 1
-cd "$MYGITPATH" || exit 1
-git clone "$REPOURL" || exit 1
-# popd || exit 1
-cd "$OLDPWD" || exit 1
+
+printf "gitpath: %s\nrepo_url: %s\nrepo_name: %s\n" "${my_git_path}" "${repo_url}" "${repo_name}"
+
+cd "${my_git_path}" || exit 1
+git clone "${repo_url}" || exit 1
+cd "${OLDPWD}" || exit 1
 exit 0
diff --git a/gitxf b/gitxf
--- a/gitxf
+++ b/gitxf
@@ -1,52 +1,51 @@
 #!/bin/bash
 # hacked together way of switching between github gitlab
-# stop script if any step fails
-set -eou pipefail
-ACTION="$1"
-REPO="$2"
+my_action="${1}"
+my_repo="${2}"
 
-pushd "$REPO"
-if [ -z "$REPO" ]; then
+# pushd "$my_repo"
+cd "${my_repo}" || exit 1
+
+if [ -z "${my_repo}" ]; then
     /usr/bin/figlet "ERROR!!"
-    printf "ERROR: Please include repo name followed by filename or \* \(glob\) for entire dir.\n"
+    printf "ERROR: Please include my_repo name followed by filename or \* \(glob\) for entire dir.\n"
   exit 1
 fi
 
-if [[ "$ACTION" == "push" ]]; then
+if [[ "${my_action}" == "push" ]]; then
     /usr/bin/git status || exit 1
     read -p "Would you like to push changes?: " -n 1 -r
-    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+    if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
             /usr/bin/git add . || exit 1
-        elif [[ "$REPLY" =~ ^[Nn]$ ]]; then
+        elif [[ "${REPLY}" =~ ^[Nn]$ ]]; then
             printf "\n%s" "No Changes Pushed" || exit 1
             sleep 0.5
-            exit
+            exit 0
         fi
 
     printf "\n%s" "Create Comment: "
-    read -r MESSAGE
-
-        /usr/bin/git commit -m "$MESSAGE" || exit 1
-        /usr/bin/git push || exit 1
-        
+    read -r my_mesg
+	/usr/bin/git commit -m "${my_mesg}" || exit 1
+	/usr/bin/git push || exit 1
     /usr/bin/figlet "PUSH COMPLETE!!"
-    popd || exit 1
-    sleep 0.5
-    exit 0
-elif [[ "$ACTION" == "pull" ]]; then
+
+elif [[ "${my_action}" == "pull" ]]; then
     /usr/bin/git pull --rebase
     /usr/bin/figlet "PULL COMPLETE!!"
-    popd || exit 1
-    sleep 0.5
-    exit 0
-elif [[ "$ACTION" == "check" ]]; then
+
+elif [[ "${my_action}" == "check" ]]; then
     /usr/bin/git remote update && git status -uno
     exit 0
+
 else
     /usr/bin/figlet "ERROR!!"
-    printf "ERROR! Usage:  gitxf [push or pull or check] [repo_name]\n"
-    popd || exit 1
+    printf "ERROR! Usage:  gitxf [push or pull or check] [my_repo_name]\n"
+	cd "${OLDPWD}" || exit 1
     sleep 0.5
-    exit 1
+	exit 1
+
 fi
+sleep 0.5
+cd "${OLDPWD}" || exit 1
+exit 0
 
diff --git a/gpush b/gpush
--- a/gpush
+++ b/gpush
@@ -3,50 +3,50 @@
 # USE shift+tab to select multiple items
 # (not implemented properly yet) # if preview of file is there use -- alt+j and alt+k down/up respectively for the preview of file contents
 set -o pipefail
-REQUIREMENTS=("fzf")
-for SINGLE in "${REQUIREMENTS[@]}"; do
-	if ! command -v "$SINGLE" &>/dev/null; then
-		printf "\n\t%s not found\n" "$SINGLE"
+my_reqs=("fzf")
+for each_single in "${my_reqs[@]}"; do
+	if ! command -v "${each_single}" &>/dev/null; then
+		printf "\n\t%s not found\n" "${each_single}"
 	# do you want to install?
 		read -p "Would you like to install?: " -n 1 -r
-		if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+		if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
 			if [[ -d "/etc/apt" ]]; then
-				sudo apt install "$SINGLE" || exit 1
+				sudo apt install "$each_single" || exit 1
 			elif [[ -d "/etc/pacman.d" ]]; then
-				sudp pacman -S "$SINGLE" || exit 1
+				sudp pacman -S "${each_single}" || exit 1
 			else
-				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$SINGLE" && exit 1
+				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "${each_single}" && exit 1
 			fi
 		else
 			printf "exiting program" && exit 0
 		fi
 	fi
 done
-if [[ "$1" = "\*" ]]; then
+if [[ "${1}" = "\*" ]]; then
 	git add .
-	read -p "Add commit message: " -r MESSAGE
-	[[ "$MESSAGE" ]] || exit 1
-	git commit -m "$MESSAGE"
+	read -p "Add commit my_mesg: " -r my_mesg
+	[[ "${my_mesg}" ]] || exit 1
+	git commit -m "${my_mesg}"
 	git push
 	exit 0
 else
 	/usr/bin/git status -uall -s | sort -u || exit 1
-	UNTRACKEDFILES="$(/usr/bin/git status -uall -s | sort -u | /usr/bin/fzf -m --prompt="Add Files : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" GPUSH ")" 
+	untracked_files="$(/usr/bin/git status -uall -s | sort -u | /usr/bin/fzf -m --prompt="Add Files : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" GPUSH ")" 
 
-	if [[ "$UNTRACKEDFILES" ]]; then
-		for FILE in $(printf '%s' "$UNTRACKEDFILES" | awk '{print $NF}'); do
-			git add "$FILE"
+	if [[ "${untracked_files}" ]]; then
+		for my_file in $(printf '%s' "${untracked_files}" | awk '{print $NF}'); do
+			git add "${my_file}"
 		done
 
 		read -p "Would you like to Commit?(Y/n): " -n 1 -r
-		if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+		if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
 			printf "\n"
-			read -p "Add commit MESSAGE: " -r MESSAGE
-			[[ -n "$MESSAGE" ]] || exit 1
-			git commit -m "$MESSAGE"
+			read -p "Add commit my_mesg: " -r my_mesg
+			[[ -n "${my_mesg}" ]] || exit 1
+			git commit -m "${my_mesg}"
 			printf "\n"
 			read -p "Would you like to Push?(Y/n): " -n 1 -r
-			if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+			if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
 				git push || exit 1
 				printf "\nExiting Program\n" && exit 0
 			else
diff --git a/helpxf b/helpxf
--- a/helpxf
+++ b/helpxf
@@ -1,25 +1,26 @@
 #!/bin/bash
+# will print out the help menu of any command
 # set -eou pipefail
 
 if ! /usr/bin/pidof /usr/bin/tmux &>/dev/null; then
 # 	get command or keyword/phrase
-	read -r -p "help menu: " QUERY
-	[ "$QUERY" ] || exit 1
+	read -r -p "help menu: " my_query
+	[ "${my_query}" ] || exit 1
 # 	check if command is a builtin
-	if ! command -v "$QUERY" &>/dev/null; then
-		printf "\n\t%s not found\n" "$QUERY" && exit 1
+	if ! command -v "${my_query}" &>/dev/null; then
+		printf "\n\t%s not found\n" "${my_query}" && exit 1
 	else
-		"$QUERY" --help 2>&1 | \less || exit 1
+		"${my_query}" --help 2>&1 | \less || exit 1
 		exit 0
 	fi
 # if /usr/bin/pidof /usr/bin/tmux &>/dev/null; then
 elif /usr/bin/pidof /usr/bin/tmux &>/dev/null; then
-	read -r -p "help menu: " QUERY
-	[ "$QUERY" ] || exit 1
-	if ! command -v "$QUERY" &>/dev/null; then
-		printf "\n\t%s not found\n" "$QUERY" && exit 1
+	read -r -p "help menu: " my_query
+	[ "${my_query}" ] || exit 1
+	if ! command -v "${my_query}" &>/dev/null; then
+		printf "\n\t%s not found\n" "${my_query}" && exit 1
 	else
-		tmux neww bash -c "$QUERY --help 2>&1 | \less" || exit 1
+		tmux neww bash -c "${my_query} --help 2>&1 | \less" || exit 1
 		exit 0
 	fi
 fi
diff --git a/manxf b/manxf
--- a/manxf
+++ b/manxf
@@ -1,22 +1,22 @@
 #!/bin/bash
 # check if fzf and apropos are installed, install if not
 set -eou pipefail
-REQUIREMENTS=("fzf" "apropos")
+my_reqs=("fzf" "apropos")
 
-for SINGLE in "${REQUIREMENTS[@]}"; do
-	if ! command -v "$SINGLE" &>/dev/null; then
-		printf "\n\t%s not found\n" "$SINGLE"
+for each_single in "${my_reqs[@]}"; do
+	if ! command -v "${each_single}" &>/dev/null; then
+		printf "\n\t%s not found\n" "${each_single}"
 # 	    do you want to install?
 		read -p "Would you like to install?: " -n 1 -r
 		if [ "$REPLY" =~ ^[Yy]$ ]; then
 # 			if command -v apt &>/dev/null; then
 			if [ -d "/etc/apt" ]; then
-				sudo apt install "$SINGLE" || exit 1
+				sudo apt install "${each_single}" || exit 1
 # 			elif command -v packman &>/dev/null; then
 			elif [ -d "/etc/pacman.d" ]; then
-				sudp pacman -S "$SINGLE" || exit 1
+				sudp pacman -S "${each_single}" || exit 1
 			else
-				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$SINGLE" && exit 1
+				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "${each_single}" && exit 1
 			fi
 		else
 			printf "exiting program" && exit 0
@@ -25,30 +25,30 @@ for SINGLE in "${REQUIREMENTS[@]}"; do
 done
 
 # get command or keyword/phrase
-read -r -p "manpages: " QUERY
-[ "$QUERY" ] || exit 1
+read -r -p "manpages: " my_query
+[ "${my_query}" ] || exit 1
 
 # check if command is a builtin
-if [ "$(type -ta "$QUERY" | head -1)" == "builtin" ] && [ "$QUERY" != "test" ]; then
-	tmux neww bash -c "man $(echo "$SHELL" | awk -F'/' '{print $NF}') | \less '+/$QUERY\ \['" || exit 1
+if [ "$(type -ta "${my_query}" | head -1)" == "builtin" ] && [ "${my_query}" != "test" ]; then
+	tmux neww bash -c "man $(echo "${SHELL}" | awk -F'/' '{print $NF}') | \less '+/${my_query}\ \['" || exit 1
 
 # check if there is manpage
-elif [ "$(apropos "$QUERY" &>/dev/null;printf '%s' "$?")" == "0" ] ; then
-	if [ "$QUERY" == "test" ]; then
-		tmux neww bash -c "man $QUERY" || exit 1
+elif [ "$(apropos "${my_query}" &>/dev/null;printf '%s' "$?")" == "0" ] ; then
+	if [ "${my_query}" == "test" ]; then
+		tmux neww bash -c "man ${my_query}" || exit 1
 		exit 0
 	else
-		SELECTED="$(apropos "$QUERY" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)"
-		[ "$SELECTED" ] || exit 1
+		my_selected="$(apropos "${my_query}" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)"
+		[ "${my_selected}" ] || exit 1
 # 		select and open manpage
-		if [ -n "$SELECTED" ]; then
-			tmux neww bash -c "man $(echo -e  "$SELECTED" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
+		if [ -n "${my_selected}" ]; then
+			tmux neww bash -c "man $(echo -e  "${my_selected}" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
 			exit 0
 		fi
 	fi
 
 # check if there is not a manpage
-elif [ "$(apropos "$QUERY" &>/dev/null;printf '%s' "$?")" == "16" ]; then
+elif [ "$(apropos "${my_query}" &>/dev/null;printf '%s' "$?")" == "16" ]; then
 	exit 16
 # 	printf "%s" "Unable to find man with keyword/phrase or builtin command to lookup." && exit 16
 
diff --git a/searchxf b/searchxf
--- a/searchxf
+++ b/searchxf
@@ -1,20 +1,21 @@
 #!/bin/bash
+# search manual pages 
 # check if fzf and apropos are installed, install if not
 set -eou pipefail
-REQUIREMENTS=("fzf" "apropos")
+my_reqs=("fzf" "apropos")
 
-for SINGLE in "${REQUIREMENTS[@]}"; do
-	if ! command -v "$SINGLE" &>/dev/null; then
-		printf "\n\t%s not found\n" "$SINGLE"
+for each_single in "${my_reqs[@]}"; do
+	if ! command -v "$each_single" &>/dev/null; then
+		printf "\n\t%s not found\n" "$each_single"
 # 	    do you want to install?
 		read -p "Would you like to install?: " -n 1 -r
 		if [ "$REPLY" =~ ^[Yy]$ ]; then
 			if [ -d "/etc/apt" ]; then
-				sudo apt install "$SINGLE" -y || exit 1
+				sudo apt install "$each_single" -y || exit 1
 			elif [ -d "/etc/pacman.d" ]; then
-				sudp pacman -S "$SINGLE" || exit 1
+				sudp pacman -S "$each_single" || exit 1
 			else
-				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$SINGLE" && exit 1
+				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$each_single" && exit 1
 			fi
 		else
 			printf "exiting program" && exit 0
@@ -24,23 +25,23 @@ done
 
 # server
 # get command or keyword/phrase
-read -r -p "query: " QUERY
-[ "$QUERY" ] || exit 1
+read -r -p "my_query: " my_query
+[ "$my_query" ] || exit 1
 
 # check if command is a builtin
-if [ $(type -ta "$QUERY" | head -1) == "builtin" ]; then
-	man "$(echo "$SHELL" | awk -F'/' '{print $NF}')" 2>&1 | \less "+/$QUERY\ \[" || exit 1
+if [ $(type -ta "$my_query" | head -1) == "builtin" ]; then
+	man "$(echo "$SHELL" | awk -F'/' '{print $NF}')" 2>&1 | \less "+/$my_query\ \[" || exit 1
 
 # check if there is not a manpage
-elif [ $(apropos "$QUERY" &>/dev/null;echo "$?") == "16" ]; then
+elif [ $(apropos "$my_query" &>/dev/null;echo "$?") == "16" ]; then
 	printf "%s\n" "Unable to find man with keyword/phrase or builtin command to lookup." && exit 16
 
 # check if there is manpage
-elif [ $(apropos "$QUERY" &>/dev/null;echo "$?") == "0" ]; then
-	SELECTED=$(apropos "$QUERY" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)
+elif [ $(apropos "$my_query" &>/dev/null;echo "$?") == "0" ]; then
+	my_selected=$(apropos "$my_query" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)
 # select and open manpage
-	if [ "$SELECTED" ]; then
-		man "$(echo -e  "$SELECTED" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
+	if [ "$my_selected" ]; then
+		man "$(echo -e  "$my_selected" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
 	fi
 else
 	printf "%s\n" "Unable to complete request for some reason" && exit 1
diff --git a/update-alacritty b/update-alacritty
--- a/update-alacritty
+++ b/update-alacritty
@@ -18,42 +18,45 @@ cd "${HOME}/Gits/alacritty" || exit 1
 VERSION="0.1"
 VERBOSE="FALSE"
 CHK_VERS="FALSE"
-binDest="/usr/local/bin/"
-binFile="target/release/alacritty"
-man1Dest="/usr/share/man/man1/"
-man5Dest="/usr/share/man/man5/"
-alacrittyManFiles="extra/man/alacritty.1.scd extra/man/alacritty-msg.1.scd extra/man/alacritty.5.scd extra/man/alacritty-bindings.5.scd"
+bin_dest="/usr/local/bin/"
+bin_file="target/release/alacritty"
+man1_dest="/usr/share/man/man1/"
+man5_dest="/usr/share/man/man5/"
+man_files="extra/man/alacritty.1.scd extra/man/alacritty-msg.1.scd extra/man/alacritty.5.scd extra/man/alacritty-bindings.5.scd"
 
 usageMessage () {
-    CMD_ECHO="${GBL_ECHO:-echo -e }"
-    $CMD_ECHO ""
-    $CMD_ECHO "${1:+Program: ${1}}${2:+        }"
-    $CMD_ECHO ""
-    $CMD_ECHO "\tVersion: ${VERSION}"
-    $CMD_ECHO "
-This program checks if the local Alacritty repo is behind, if so, pull latest,
-build and copy the binary, manuals, and icon files to the proper directories.
+    printf "
+%s
+%s%s
+%s
+\tVersion: %s
 
-Usage: ${1##*/} [-?hvV]
+This program checks if the local repo for Alacritty is up-to-date, if not,
+update repo, build binary, build manual pages, change to correct permission and
+copy them to the proper directories.
+Assumes repository is in ~/Gits.
+
+Usage: %s [-?hvV]
 
   Where:
-    -v = Version -- show current version, then exit 
+    -v = Version -- just the version is displayed
     -V = Verbose -- debug output displayed
-    -h = Help   -- display this message
-    -? = Help   -- display this message
+    -h = Help    -- display this message
+    -? = Help    -- display this message
 
-"
+# Author: Jb Williams (jb.williams016@gmail.com)
+" "" "${1:+Program: ${1}}" "" "" "${2}" "${1##*/}"
 }
 
 checkUpdate () {
     # check if remote repo is ahead of local repo
     posibleUpdate="$(/usr/bin/git remote update >/dev/null 2>&1 && /usr/bin/git status -uno | /usr/bin/grep -o "up to date")"
-    if [ "$posibleUpdate" = "up to date" ]; then
+    if [ "${posibleUpdate}" = "up to date" ]; then
         printf "Git Repo already up to date!\n" && exit 0
     else
         printf "Seems there is an Update! Continue? (Y/N): "
         read -r reply
-        case $reply in
+        case ${reply} in
             [Yy])
                 ;;
             *)
@@ -65,10 +68,11 @@ checkUpdate () {
 
 changePerm () {
     ## takes in file name if its the binary 755, if man 644
-    if [ "$(echo "$1" | /usr/bin/awk -F'/' '{print $NF}')" = "alacritty" ]; then
-        /usr/bin/sudo chmod u=rwx,g=rx,o=rx "$1" || printf "%s %s!\n" "failed changing perm on" "${1}${2}"
-    elif [ "$(echo "$1" | /usr/bin/awk -F'.' '{print $NF}')" = "gz" ]; then
-        /usr/bin/sudo chmod u=rw,g=r,o=r  "$1" || printf "%s %s!\n" "failed changing perm on" "${1}"
+    if [ "$(echo "${1}" | /usr/bin/awk -F'/' '{print $NF}')" = "alacritty" ]; then
+#         /usr/bin/sudo chmod u=rwx,g=rx,o=rx "$1" || printf "%s %s!" "failed changing perm on" "${1}${2}"
+        /usr/bin/sudo chmod u=rwx,g=rx,o=rx "${1}" || printf "%s %s%s!" "failed changing perm on" "${1}" "${2}"
+    elif [ "$(echo "${1}" | /usr/bin/awk -F'.' '{print $NF}')" = "gz" ]; then
+        /usr/bin/sudo chmod u=rw,g=r,o=r  "${1}" || printf "%s %s!\n" "failed changing perm on" "${1}"
     else
         printf "%s!\n" "some error, wasn't passed anything named 'alacritty' or 'gz'" && exit 2
     fi
@@ -76,7 +80,7 @@ changePerm () {
 }
 
 copyFile () {
-    /usr/bin/sudo cp "$1" "$2" || printf "%s %s %s!\n" "failed to copy" "$1" "$2"
+    /usr/bin/sudo cp "${1}" "${2}" || printf "%s %s %s!\n" "failed to copy" "${1}" "${2}"
     return
 }
 
@@ -87,11 +91,11 @@ buildBin () {
 }
 
 buildMan () {
-    oldFilename="$1"
-    newFilename="$(echo "$oldFilename" | /usr/bin/awk -F'.' '{print $1"."$2}')"
-#   whichMan="$(echo "$newFilename" | /usr/bin/awk -F'.' '{print $2}')"
-    /usr/bin/scdoc < "$oldFilename" >> "$newFilename" || printf "%s %s!\n" "failed making sdoc from" "$oldFilename"
-    /usr/bin/gzip -f "$newFilename" || printf "%s %s!\n" "failed gzipping" "$newFilename"
+    old_filename="${1}"
+    new_filename="$(echo "${old_filename}" | /usr/bin/awk -F'.' '{print $1"."$2}')"
+#   which_man="$(echo "$new_filename" | /usr/bin/awk -F'.' '{print $2}')"
+    /usr/bin/scdoc < "${old_filename}" >> "${new_filename}" || printf "%s %s!\n" "failed making sdoc from" "${old_filename}"
+    /usr/bin/gzip -f "${new_filename}" || printf "%s %s!\n" "failed gzipping" "${new_filename}"
     return
 }
 
@@ -101,16 +105,15 @@ do
     case "$OPTION" in
         v) CHK_VERS="TRUE";;
         V) VERBOSE="TRUE";;
-        \?) usageMessage "$0" && exit 1 ;;
-        h) usageMessage "$0" && exit 1 ;;
+        \?|h) usageMessage "${0}" "${VERSION}" && exit 1 ;;
     esac
 done
 
 shift $((OPTIND - 1))
 # set based on flags given
-[ "$VERBOSE" = "TRUE" ] && set -x
-[ "$CHK_VERS" = "TRUE" ] && printf "#\n%s\n%s %s\n" "# $0" "## Version........: " "$VERSION"
-# [ "$CHK_VERS" = "TRUE" ] && printf "%s" "## Version........: $VERSION" && exit 0
+[ "${VERBOSE}" = "TRUE" ] && set -x
+[ "${CHK_VERS}" = "TRUE" ] && printf "#\n#\t%s\n" "${0##*/}"
+[ "${CHK_VERS}" = "TRUE" ] && printf "%s\n" "# Version........: ${VERSION}" && exit 0
 
 # check if local repo is behind
 checkUpdate || exit 1
@@ -128,25 +131,25 @@ fi
 buildBin || exit 1
 
 # change perm of binary
-changePerm "$binFile" || exit 1
+changePerm "${bin_file}" || exit 1
 
 # copy binary to destination
-copyFile "$binFile" "$binDest" || exit 1
+copyFile "${bin_file}" "${bin_dest}" || exit 1
 
 # build man files
-for manFile in $alacrittyManFiles; do
-    buildMan "$manFile" || exit 1
+for each_manfile in ${man_files}; do
+    buildMan "${each_manfile}" || exit 1
 done
 
 # change file permissions then copy them to proper man destination
-for manFile in $alacrittyManFiles; do
-    gzFile="$(/usr/bin/ls "$manFile" | /usr/bin/awk -F'.' '{print $1"."$2".gz"}')"
-    whichMan="$(/usr/bin/ls "$manFile" | /usr/bin/awk -F'.' '{print $2}')"
-    changePerm "$gzFile" || exit 1
-    if  [ "$whichMan"  = 1 ]; then
-        copyFile "$gzFile" "$man1Dest" || exit 1
-    elif  [ "$whichMan"  = 5 ]; then
-        copyFile "$gzFile" "$man5Dest" || exit 1
+for each_manfile in ${man_files}; do
+    gz_file="$(/usr/bin/ls "${each_manfile}" | /usr/bin/awk -F'.' '{print $1"."$2".gz"}')"
+    which_man="$(/usr/bin/ls "${each_manfile}" | /usr/bin/awk -F'.' '{print $2}')"
+    changePerm "${gz_file}" || exit 1
+    if  [ "${which_man}"  = 1 ]; then
+        copyFile "${gz_file}" "${man1_dest}" || exit 1
+    elif  [ "${which_man}"  = 5 ]; then
+        copyFile "${gz_file}" "${man5_dest}" || exit 1
     fi
 done
 
@@ -158,7 +161,7 @@ done
 /usr/bin/sudo cp extra/logo/alacritty-term+scanlines.svg /usr/share/pixmaps/Alacritty.svg \
     && /usr/bin/sudo chmod u=rw,g=r,o=r /usr/share/pixmaps/Alacritty.svg
 
-cd "$OLDPWD" || exit 1
+cd "${OLDPWD}" || exit 1
 exit 0
 
 ## requires
